import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated from the repo's top-level `docs/` folder (../../docs).
 * As docs are added/reorganized there, the sidebar follows automatically.
 * Fine-grained ordering can be controlled with `_category_.json` files or
 * `sidebar_position` front matter per doc.
 */
const sidebars: SidebarsConfig = {
	platformSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
